version: "3.2"
services:
  broker_service:
    image: tonymaithanh/hmmportalbroker:latest
    container_name: broker_service
    restart: always
    ports:
      - 443:5678
    volumes:
      - broker_service-volume:/app/Debug_Log
  backend_service:
    image: tonymaithanh/finkitbackend:latest
    container_name: backend_service
    restart: always
    ports:
      - 80:5001
    volumes:
      - backend_service-volume:/app/Debug_Log
networks:
  monitoring:
volumes:
  broker_service-volume:
    external: false   
  backend_service-volume:
    external: false
