version: "3.2"
services:
  broker_service:
    image: tonymaithanh/hmmportalbroker:latest
    container_name: broker_service
    restart: always
    ports:
      - 443:443
      - 1234:1234
    volumes:
      - type: bind
        source: /root/broker_service-appsettings.json
        target: /app/appsettings.json
      - broker_service-volume:/app/Debug_Log
  backend_service:
    image: tonymaithanh/finkitbackend:latest
    container_name: backend_service
    restart: always
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /root/backend_service-appsettings.json
        target: /app/appsettings.json
      - backend_service-volume:/app/Debug_Log
  ticker_service:
    image: tonymaithanh/hmmportalservicetickcandle:latest
    container_name: ticker_service
    restart: always
    ports:
      - 5002:5002
    volumes:
      - type: bind
        source: /root/ticker_service-appsettings.json
        target: /app/appsettings.json
volumes:
  broker_service-volume:
    external: false   
  backend_service-volume:
    external: false
